local settings = {
	autoread = true,
	backup = false,
	cmdheight = 1,
	colorcolumn = { "120" },
	completeopt = "menuone,noselect,preview",
	conceallevel = 1,
	cursorline = false,
	errorbells = false,
	expandtab = true,
	fileencoding = "utf-8",
	mouse = "nvi",
	number = true,
	numberwidth = 3,
	pumheight = 10,
	scrolloff = 8,
	shiftwidth = 2,
	shortmess = "filnxtToOFWIcC",
	showmode = true,
	showtabline = 2,
	sidescrolloff = 8,
	signcolumn = "yes:1",
	smartindent = true,
	softtabstop = 2,
	spell = true,
	spelllang = { "en_us" },
	splitkeep = "screen",
	swapfile = false,
	tabstop = 2,
	termguicolors = true,
	textwidth = 120,
	timeoutlen = 1000,
	title = true,
	undodir = os.getenv("HOME") .. "/.vim/undodir",
	undofile = true,
	updatetime = 50,
	wrap = true,
	writebackup = false,
}

for setting, value in pairs(settings) do
	vim.opt[setting] = value
end
