local settings = {
	autoindent = true,
	autoread = true,
	backspace = { "start", "eol", "indent" },
	backup = false,
	cmdheight = 1,
	colorcolumn = { "80", "120" },
	completeopt = "menuone,noselect,preview",
	conceallevel = 1,
	cursorline = false,
	errorbells = false,
	expandtab = true,
	fileencoding = "utf-8",
	fillchars = {
		diff = "",
		fold = " ",
		eob = " ",
		horiz = "━",
		horizup = "┻",
		horizdown = "┳",
		vert = "┃",
		vertleft = "┫",
		vertright = "┣",
		verthoriz = "╋",
		foldclose = "",
		foldopen = "",
		foldsep = " ",
	},
	list = true,
	listchars = {
		-- eol = "↲",
		tab = "» ",
		nbsp = "␣",
		trail = "·",
		extends = "→",
		precedes = "←",
	},
	mouse = "a",
	number = true,
	numberwidth = 3,
	pumheight = 10,
	relativenumber = true,
	scrolloff = 8,
	shiftwidth = 2,
	shortmess = "filnxtToOFWIcC",
	showbreak = "↪",
	showmode = true,
	showtabline = 0,
	sidescrolloff = 8,
	signcolumn = "yes:1",
	smartindent = true,
	softtabstop = 2,
	spell = true,
	spelllang = { "en_us" },
	splitkeep = "screen",
	swapfile = false,
	tabstop = 2,
	termguicolors = true,
	textwidth = 120,
	timeoutlen = 1000,
	title = true,
	undodir = os.getenv("HOME") .. "/.vim/undodir",
	undofile = true,
	updatetime = 50,
	wrap = true,
	writebackup = false,
}

for setting, value in pairs(settings) do
	vim.opt[setting] = value
end

vim.g.editorconfig = true
vim.opt.isfname:append("@-@")
vim.opt.clipboard:append("unnamedplus")
