return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	-- We need to enable markview before treesitter, so this is a hack to do that
	dependencies = { "OXY2DEV/markview.nvim" },
	opts = {
		ensure_installed = {
			"asm",
			"bash",
			"c",
			"clojure",
			"cmake",
			"comment",
			"cpp",
			"css",
			"csv",
			"diff",
			"dockerfile",
			"ebnf",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"gotmpl",
			"gowork",
			"gpg",
			"graphql",
			"haskell",
			"helm",
			"html",
			"java",
			"javascript",
			"jq",
			"json",
			"latex",
			"lua",
			"luadoc",
			"luap",
			"make",
			"markdown",
			"markdown_inline",
			"nix",
			"php",
			"phpdoc",
			"python",
			"regex",
			"rust",
			"scala",
			"sql",
			"ssh_config",
			"swift",
			"templ",
			"terraform",
			"toml",
			"tsv",
			"tsx",
			"typescript",
			"typst",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"zig",
		},
		sync_install = false,
		highlight = { enable = true },
		indent = { enable = true },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-space>",
				node_incremental = "<C-space>",
				scope_incremental = false,
			}
		},
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end
}
